export const TOOL_LOADING = 'TOOL_LOADING';
export const TOOL_FAILED = 'TOOL_FAILED';
export const ADD_TOOL = 'ADD_TOOL';

export const CONTACT_LOADING = 'CONTACT_LOADING';
export const CONTACT_FAILED = 'CONTACT_FAILED';
export const ADD_CONTACT = 'ADD_CONTACT';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';